module:
  automated_cron: 0
  backup_migrate: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  classy_paragraphs: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  disqus: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facebook_pixel: 0
  fences: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  imageapi_optimize: 0
  link: 0
  menu_item_extras: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  sharethis: 0
  shortcut: 0
  simple_gmap: 0
  slick: 0
  slick_paragraphs: 0
  slick_ui: 0
  slick_views: 0
  sp_solar_calculator: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  user_redirect: 0
  video_embed_field: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  contribute: 1
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  sunpower: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
