unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: true
log: true
element_name: homepage
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  node_article_form: false
  node_career_form: false
  node_employee_form: false
  node_faq_form: false
  node_landing_page_form: false
  node_media_form: false
  node_page_form: false
  node_portfolio_item_form: false
  node_service_form: false
  node_store_form: false
  node_webform_form: false
  comment_comment_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
