google_adwords_signup.settings:
  type: mapping
  label: Settings
  mapping:
    google_adwords_user_conversion_color:
      type: string
    google_adwords_user_conversion_id:
      type: integer
    google_adwords_user_conversion_language:
      type: 'NULL'
    google_adwords_user_conversion_format:
      type: string
    google_adwords_external_script:
      type: string
