drupalchat.settings:
  type: config_object
  label: 'DrupalChat Config'
  mapping:
    drupalchat_polling_method:
      type: integer
    drupalchat_external_api_key:
      type: string
    drupalchat_app_id:
      type: string
    drupalchat_path_visibility:
      type: string
    drupalchat_path_pages:
      type: string
    drupalchat_rel:
      type: integer
    drupalchat_ur_name:
      type: string
    drupalchat_notification_sound:
      type: integer
    drupalchat_user_picture:
      type: integer
    drupalchat_enable_smiley:
      type: integer
    drupalchat_log_messages:
      type: integer
    drupalchat_anon_prefix:
      type: string
    drupalchat_anon_use_name:
      type: integer
    drupalchat_user_latency:
      type: integer
    drupalchat_refresh_rate:
      type: integer
    drupalchat_enable_chatroom:
      type: integer
    drupalchat_session_caching:
      type: integer